PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX ore: <http://www.openarchives.org/ore/terms/>
PREFIX html: <http://www.w3.org/1999/xhtml/vocab#>

SELECT ?title ?creator ?glam_inst ?img_url
WHERE {
?object edm:type "IMAGE" .
?object dc:title ?title .
?object dc:creator ?creator .
?object ore:proxyIn ?local_aggr .
OPTIONAL{ ?local_aggr edm:object ?img_url . } .
?local_aggr edm:provider ?glam_inst .

?object ore:proxyFor ?cho .
?eur_aggr edm:aggregatedCHO ?cho .
?eur_aggr a edm:EuropeanaAggregation .

?eur_aggr edm:country 'belgium' .
}
OFFSET 1000
LIMIT 500
